In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("flipkart_orders_for_sql.csv")

In [3]:
df

,order_id_pk,customer_name,product_name,returns,review_date,rating,review_text,price
0,ORD000001,Omaja Badami,Kitchenware,Yes,11-04-2025,4,"Great kitchenware, exactly as described. Very ...",1110.0
1,ORD000003,Eiravati Pradhan,Groceries,No,14-11-2025,2,"Disappointed with this groceries, quality is n...",100.0
2,ORD000004,Tara Varughese,Electronics,No,03-06-2023,5,"Great electronics, exactly as described. Very ...",49600.0
3,ORD000005,Nidhi Sekhon,Electronics,No,21-09-2023,2,"Received a damaged electronics, had to return it.",19020.0
4,ORD000007,Aarav Nagy,Groceries,No,22-04-2023,5,"Great groceries, exactly as described. Very ha...",550.0
...,...,...,...,...,...,...,...,...
7953,ORD009996,Sarthak Puri,Shoes,No,12-07-2023,3,"The shoes is okay, does the job but nothing sp...",1580.0
7954,ORD009997,Kamala Keer,Books,Yes,20-12-2023,4,"Excellent quality for the price, would buy boo...",340.0
7955,ORD009998,Anjali Dasgupta,Beauty Products,Yes,17-08-2024,4,"Fast delivery, beauty products exceeded my exp...",2070.0
7956,ORD009999,Falak Gulati,Groceries,No,20-08-2024,3,"The groceries is okay, does the job but nothin...",250.0
7957,ORD010000,Lucky Balakrishnan,Electronics,No,30-06-2025,5,"Excellent quality for the price, would buy ele...",30860.0

In [4]:
df.shape

(7958, 8)

In [5]:
df.describe()

            rating         price
count  7958.000000   7958.000000
mean      3.880372   8675.816788
std       1.151692  13691.735007
min       1.000000     50.000000
25%       3.000000   1080.000000
50%       4.000000   2260.000000
75%       5.000000   8525.000000
max       5.000000  59990.000000

In [6]:
df.head()

,order_id_pk,customer_name,product_name,returns,review_date,rating,review_text,price
0,ORD000001,Omaja Badami,Kitchenware,Yes,11-04-2025,4,"Great kitchenware, exactly as described. Very ...",1110.0
1,ORD000003,Eiravati Pradhan,Groceries,No,14-11-2025,2,"Disappointed with this groceries, quality is n...",100.0
2,ORD000004,Tara Varughese,Electronics,No,03-06-2023,5,"Great electronics, exactly as described. Very ...",49600.0
3,ORD000005,Nidhi Sekhon,Electronics,No,21-09-2023,2,"Received a damaged electronics, had to return it.",19020.0
4,ORD000007,Aarav Nagy,Groceries,No,22-04-2023,5,"Great groceries, exactly as described. Very ha...",550.0

In [7]:
df.tail()

,order_id_pk,customer_name,product_name,returns,review_date,rating,review_text,price
7953,ORD009996,Sarthak Puri,Shoes,No,12-07-2023,3,"The shoes is okay, does the job but nothing sp...",1580.0
7954,ORD009997,Kamala Keer,Books,Yes,20-12-2023,4,"Excellent quality for the price, would buy boo...",340.0
7955,ORD009998,Anjali Dasgupta,Beauty Products,Yes,17-08-2024,4,"Fast delivery, beauty products exceeded my exp...",2070.0
7956,ORD009999,Falak Gulati,Groceries,No,20-08-2024,3,"The groceries is okay, does the job but nothin...",250.0
7957,ORD010000,Lucky Balakrishnan,Electronics,No,30-06-2025,5,"Excellent quality for the price, would buy ele...",30860.0

In [8]:
df.isna().sum()

order_id_pk      0
customer_name    0
product_name     0
returns          0
review_date      0
rating           0
review_text      0
price            0
dtype: int64

In [13]:
df["returns"].count()

np.int64(7958)

In [17]:
(df["returns"]=="Yes").sum()

np.int64(972)

In [20]:
(df["price"]>40000).sum()

np.int64(527)

In [31]:
df[(df["price"]>100) & (df["product_name"]=="Kitchenware")].sum()

order_id_pk      ORD000001ORD000018ORD000039ORD000042ORD000052O...
customer_name    Omaja BadamiAayush DhingraAnusha RajaLakshit M...
product_name     KitchenwareKitchenwareKitchenwareKitchenwareKi...
returns          YesNoNoNoYesNoNoNoNoNoYesNoNoNoNoNoNoNoNoNoYes...
review_date      11-04-202528-06-202330-08-202531-12-202522-01-...
rating                                                        2380
review_text      Great kitchenware, exactly as described. Very ...
price                                                    1626710.0
dtype: object

In [32]:
df[df["product_name"]=="Electronics"].sum()

order_id_pk      ORD000004ORD000005ORD000025ORD000026ORD000033O...
customer_name    Tara VarugheseNidhi SekhonOsha PatilAdya Sangh...
product_name     ElectronicsElectronicsElectronicsElectronicsEl...
returns          NoNoNoNoNoNoNoNoYesNoNoNoNoNoNoNoNoNoNoNoNoYes...
review_date      03-06-202321-09-202318-10-202530-07-202419-08-...
rating                                                        4652
review_text      Great electronics, exactly as described. Very ...
price                                                   36511990.0
dtype: object

In [34]:
(df["customer_name"]=="Omaja Badami").sum()

np.int64(10)

In [38]:
df[df["price"]==df["price"]].max()

order_id_pk                                              ORD010000
customer_name                                          Zilmil Bail
product_name                                                  Toys
returns                                                        Yes
review_date                                             31-12-2025
rating                                                           5
review_text      The toys is okay, does the job but nothing spe...
price                                                      59990.0
dtype: object

In [43]:
(df["customer_name"]=="Zilmil Bail").sum()

np.int64(14)