In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("flipkart_orders_for_sql.csv")

In [3]:
df

,order_id_pk,customer_name,product_name,returns,review_date,rating,review_text,price
0,ORD000001,Omaja Badami,Kitchenware,Yes,11-04-2025,4,"Great kitchenware, exactly as described. Very ...",1110.0
1,ORD000003,Eiravati Pradhan,Groceries,No,14-11-2025,2,"Disappointed with this groceries, quality is n...",100.0
2,ORD000004,Tara Varughese,Electronics,No,03-06-2023,5,"Great electronics, exactly as described. Very ...",49600.0
3,ORD000005,Nidhi Sekhon,Electronics,No,21-09-2023,2,"Received a damaged electronics, had to return it.",19020.0
4,ORD000007,Aarav Nagy,Groceries,No,22-04-2023,5,"Great groceries, exactly as described. Very ha...",550.0
...,...,...,...,...,...,...,...,...
7953,ORD009996,Sarthak Puri,Shoes,No,12-07-2023,3,"The shoes is okay, does the job but nothing sp...",1580.0
7954,ORD009997,Kamala Keer,Books,Yes,20-12-2023,4,"Excellent quality for the price, would buy boo...",340.0
7955,ORD009998,Anjali Dasgupta,Beauty Products,Yes,17-08-2024,4,"Fast delivery, beauty products exceeded my exp...",2070.0
7956,ORD009999,Falak Gulati,Groceries,No,20-08-2024,3,"The groceries is okay, does the job but nothin...",250.0
7957,ORD010000,Lucky Balakrishnan,Electronics,No,30-06-2025,5,"Excellent quality for the price, would buy ele...",30860.0

In [4]:
df.shape

(7958, 8)

In [5]:
df.head()

,order_id_pk,customer_name,product_name,returns,review_date,rating,review_text,price
0,ORD000001,Omaja Badami,Kitchenware,Yes,11-04-2025,4,"Great kitchenware, exactly as described. Very ...",1110.0
1,ORD000003,Eiravati Pradhan,Groceries,No,14-11-2025,2,"Disappointed with this groceries, quality is n...",100.0
2,ORD000004,Tara Varughese,Electronics,No,03-06-2023,5,"Great electronics, exactly as described. Very ...",49600.0
3,ORD000005,Nidhi Sekhon,Electronics,No,21-09-2023,2,"Received a damaged electronics, had to return it.",19020.0
4,ORD000007,Aarav Nagy,Groceries,No,22-04-2023,5,"Great groceries, exactly as described. Very ha...",550.0

In [6]:
df.tail()

,order_id_pk,customer_name,product_name,returns,review_date,rating,review_text,price
7953,ORD009996,Sarthak Puri,Shoes,No,12-07-2023,3,"The shoes is okay, does the job but nothing sp...",1580.0
7954,ORD009997,Kamala Keer,Books,Yes,20-12-2023,4,"Excellent quality for the price, would buy boo...",340.0
7955,ORD009998,Anjali Dasgupta,Beauty Products,Yes,17-08-2024,4,"Fast delivery, beauty products exceeded my exp...",2070.0
7956,ORD009999,Falak Gulati,Groceries,No,20-08-2024,3,"The groceries is okay, does the job but nothin...",250.0
7957,ORD010000,Lucky Balakrishnan,Electronics,No,30-06-2025,5,"Excellent quality for the price, would buy ele...",30860.0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7958 entries, 0 to 7957
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id_pk    7958 non-null   object
 1   customer_name  7958 non-null   object
 2   product_name   7958 non-null   object
 3   returns        7958 non-null   object
 4   review_date    7958 non-null   object
 5   rating         7958 non-null   int64
 6   review_text    7958 non-null   object
 7   price          7958 non-null   float64
dtypes: float64(1), int64(1), object(6)
memory usage: 497.5+ KB

In [9]:
df["review_text"]

0       Great kitchenware, exactly as described. Very ...
1       Disappointed with this groceries, quality is n...
2       Great electronics, exactly as described. Very ...
3       Received a damaged electronics, had to return it.
4       Great groceries, exactly as described. Very ha...
                              ...
7953    The shoes is okay, does the job but nothing sp...
7954    Excellent quality for the price, would buy boo...
7955    Fast delivery, beauty products exceeded my exp...
7956    The groceries is okay, does the job but nothin...
7957    Excellent quality for the price, would buy ele...
Name: review_text, Length: 7958, dtype: object

In [10]:
def exctract_text(text):
    total = ""
    check = True
    for i in text:
        if i == ",":
            break
        if check:
            total+=i
    return total

In [12]:
df["Specific_rating"] = df["review_text"].apply(exctract_text)

In [13]:
df

,order_id_pk,customer_name,product_name,returns,review_date,rating,review_text,price,Specific_rating
0,ORD000001,Omaja Badami,Kitchenware,Yes,11-04-2025,4,"Great kitchenware, exactly as described. Very ...",1110.0,Great kitchenware
1,ORD000003,Eiravati Pradhan,Groceries,No,14-11-2025,2,"Disappointed with this groceries, quality is n...",100.0,Disappointed with this groceries
2,ORD000004,Tara Varughese,Electronics,No,03-06-2023,5,"Great electronics, exactly as described. Very ...",49600.0,Great electronics
3,ORD000005,Nidhi Sekhon,Electronics,No,21-09-2023,2,"Received a damaged electronics, had to return it.",19020.0,Received a damaged electronics
4,ORD000007,Aarav Nagy,Groceries,No,22-04-2023,5,"Great groceries, exactly as described. Very ha...",550.0,Great groceries
...,...,...,...,...,...,...,...,...,...
7953,ORD009996,Sarthak Puri,Shoes,No,12-07-2023,3,"The shoes is okay, does the job but nothing sp...",1580.0,The shoes is okay
7954,ORD009997,Kamala Keer,Books,Yes,20-12-2023,4,"Excellent quality for the price, would buy boo...",340.0,Excellent quality for the price
7955,ORD009998,Anjali Dasgupta,Beauty Products,Yes,17-08-2024,4,"Fast delivery, beauty products exceeded my exp...",2070.0,Fast delivery
7956,ORD009999,Falak Gulati,Groceries,No,20-08-2024,3,"The groceries is okay, does the job but nothin...",250.0,The groceries is okay
7957,ORD010000,Lucky Balakrishnan,Electronics,No,30-06-2025,5,"Excellent quality for the price, would buy ele...",30860.0,Excellent quality for the price

In [14]:
def Text_inormation(text):
    check = False
    Total = ""
    for i in text:
        if i == ",":
            check = True
            continue 
        if i == ".":
            check = False
            break
        if check:
            Total+=i
    return Total

In [15]:
df["Text_info"] = df["review_text"].apply(Text_inormation)

In [16]:
df

,order_id_pk,customer_name,product_name,returns,review_date,rating,review_text,price,Specific_rating,Text_info
0,ORD000001,Omaja Badami,Kitchenware,Yes,11-04-2025,4,"Great kitchenware, exactly as described. Very ...",1110.0,Great kitchenware,exactly as described
1,ORD000003,Eiravati Pradhan,Groceries,No,14-11-2025,2,"Disappointed with this groceries, quality is n...",100.0,Disappointed with this groceries,quality is not good
2,ORD000004,Tara Varughese,Electronics,No,03-06-2023,5,"Great electronics, exactly as described. Very ...",49600.0,Great electronics,exactly as described
3,ORD000005,Nidhi Sekhon,Electronics,No,21-09-2023,2,"Received a damaged electronics, had to return it.",19020.0,Received a damaged electronics,had to return it
4,ORD000007,Aarav Nagy,Groceries,No,22-04-2023,5,"Great groceries, exactly as described. Very ha...",550.0,Great groceries,exactly as described
...,...,...,...,...,...,...,...,...,...,...
7953,ORD009996,Sarthak Puri,Shoes,No,12-07-2023,3,"The shoes is okay, does the job but nothing sp...",1580.0,The shoes is okay,does the job but nothing special
7954,ORD009997,Kamala Keer,Books,Yes,20-12-2023,4,"Excellent quality for the price, would buy boo...",340.0,Excellent quality for the price,would buy books again
7955,ORD009998,Anjali Dasgupta,Beauty Products,Yes,17-08-2024,4,"Fast delivery, beauty products exceeded my exp...",2070.0,Fast delivery,beauty products exceeded my expectations
7956,ORD009999,Falak Gulati,Groceries,No,20-08-2024,3,"The groceries is okay, does the job but nothin...",250.0,The groceries is okay,does the job but nothing special
7957,ORD010000,Lucky Balakrishnan,Electronics,No,30-06-2025,5,"Excellent quality for the price, would buy ele...",30860.0,Excellent quality for the price,would buy electronics again